# Welcome to Jekyll!
#

# Site settings
title: Spectral
description: |
  Another fine responsive  
  site template freebie  
  crafted by [HTML5 UP](http://html5up.net)
owner: Gangster # or company name
first_published: 2021 # if migrating another site, the year of your first publish
email: 592242859@qq.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://GanSiH.github.io" # the base hostname & protocol for your site
social:
  twitter: https://twitter.com/<username>
  github: https://github.com/<username>
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/

# Build settings
markdown: kramdown
#sass:
#  style: compressed
